- name: MicroOS setup playbook
  #hosts: localhost
  #connection: local
  hosts: testvms
  vars:
     project: microos-setup
     ansible_remote_tmp: /tmp
     ansiblue_dir: "{{ playbook_dir }}"
     config:
       flatpak: "{{ lookup('template', 'configs/flatpak.yaml') | from_yaml }}"
       host: "{{ lookup('template', 'configs/host.yaml') | from_yaml }}"

  tasks:
    - name: Ensure directory {{ lookup('env','HOME') }}/.local/bin exists
      ansible.builtin.file:
        path: "{{ lookup('env','HOME') }}/.local/bin"
        state: directory
        mode: '0755'
      tags: [always]

    - name: Add flatpak remotes
      community.general.flatpak_remote:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        method: user
        flatpakrepo_url: "{{ item.flatpakrepo_url }}"
      loop: "{{ config.flatpak.remotes }}"
      tags: [flatpak]

    - name: Setup flatpaks
      include_tasks: playbooks/setup/setup_flatpak.yaml
      tags: [always]
      args:
        apply:
          tags: [flatpak]
      loop: "{{ config.flatpak.flatpaks }}"
      loop_control:
        loop_var: flatpak
        label: "{{ flatpak.name }}"

    - name: Configure host
      include_tasks: playbooks/setup/setup_host.yaml
      tags: [always]
      args:
        apply:
          tags: [host]
      loop: "{{ config.host }}"
      loop_control:
        loop_var: host
        label: "{{ host.name }}"
