- name: Manage overlay packages {{ task_identifier }}
  tags: [rpm-ostree]
  community.general.zypper:
    name: "{{ system_pkg.name }}"
    state: "{{ system_pkg.state }}"
  loop: "{{ host.packages }}"
  loop_control:
    loop_var: system_pkg
    label: {'name': '{{ system_pkg.name }}', 'state': '{{ system_pkg.state }}'}
  become: true
