- name: Make {{ flatpak.name }} flatpak {{ flatpak.state }} {{ 'using ' + flatpak.remote + ' remote' if flatpak.state == 'present' }}
  community.general.flatpak:
    name: "{{ flatpak.name }}"
    state: "{{ flatpak.state }}"
    method: user
    remote: "{{ flatpak.remote }}"

- name: Make local bin wrapper {{ flatpak.name }} {{ flatpak.state }} in {{ lookup('env','HOME') }}/.local/bin/
  ansible.builtin.copy:
    content: "{{ lookup('env','HOME') }}/.local/share/flatpak/app/{{ flatpak.name }}/current/active/export/bin/{{ flatpak.name }}" 
    dest: "{{ lookup('env','HOME') }}/.local/bin/{{ cmd }}"
    mode: a+x
  loop: "{{ flatpak.cmds | default([]) }}"
  loop_control:
    loop_var: cmd

- name: Create override for {{ flatpak.name }} flatpak
  ansible.builtin.shell:
    cmd: "flatpak override --user {{ override.name }} {{ flatpak.name }}"
  changed_when: false
  loop: "{{ flatpak.overrides | default([]) }}"
  loop_control:
    loop_var: override
