remotes:
  - name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: flathub-beta
    state: present
    flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo

flatpaks:
  - name: org.gimp.GIMP
    state: present
    remote: flathub-beta
    cmds: [gimp]

  - name: com.github.tchx84.Flatseal
    state: present
    remote: flathub

  - name: org.kde.neochat
    state: present
    remote: flathub
