- name: microos-test
  tasks: 
    - playbooks/host/tasks_host_default.yaml
    - playbooks/host/tasks_host_transactional_update.yaml
    - playbooks/host/tasks_host_systemd.yaml

  packages:
    - { name: exa, action: install }
    - { name: bat, action: install }
    - { name: fish, action: install }
    - { name: man, action: install }
    - { name: man-pages, action: install }

  systemd:
    user:
      - name: downloads-delete.service
        enabled: no
        state: stopped
      - name: downloads-delete.timer
        enabled: yes
        state: started
      - name: flatpak-update.service
        enabled: no
        state: stopped
      - name: flatpak-update.timer
        enabled: yes
        state: stopped
    system: {}
